--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Inaayat04/ScoreTag
build-by-default: true
branches:
- master
projects:
  ScoreTag:
    path: ""
    lint:
      phpstan: false
    icon: icon.png
...
