name: ScoreTag
version: 1.0.7
main: Inaayat\ScoreTag\Main
api:
  - 3.0.0
author: Inaayat
softdepend:
  - CombatLogger
  - EconomyAPI
  - FactionsPro
  - PiggyFactions
  - PurePerms
  - RankUp
  - RedSkyBlock
  - SeeDevice