---
##
#   _____                 _______          
#  / ____|               |__   __|         
# | (___   ___ ___  _ __ ___| | __ _  __ _ 
#  \___ \ / __/ _ \| '__/ _ \ |/ _` |/ _` |
#  ____) | (_| (_) | | |  __/ | (_| | (_| |
# |_____/ \___\___/|_|  \___|_|\__,_|\__, |
#                                     __/ |
#                                    |___/
#
# For a list of supported score tags, visit https://github.com/Inaayat04/ScoreTag
##

# The tag displayed below the player's name tag
tag: "§a§lHealth: {line} &d{hp}/{max_hp}"
# How often to update the score tags (in ticks)
update-period: 10
...
